### ISSUE TITLE
Error in pghoard.sh

### ISSUE THREAD

**Issue by eduardobaitello** [xarg/pghoard-k8s#1]
The `pghoard.sh`script contains a error.

The line:
cat /pghoard.json.template | sed "s/\"password\": \"replica\"/\"password\": \"${REPLICA_PASSWORD}\"/" | sed "s/\"user\": \"replica\"/\"**password**\": \"${REPLICA_USER}\"/" > /pghoard.json

 should be:

 cat /pghoard.json.template | sed "s/\"password\": \"replica\"/\"password\": \"${REPLICA_PASSWORD}\"/" | sed "s/\"user\": \"replica\"/\"**user**\": \"${REPLICA_USER}\"/" > /pghoard.json

**Comment by xarg** [comment]
Thanks!
